/* Authentication actions */
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE'
export const AUTH_USER = 'AUTH_USER'
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT'
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH'

/* Normal user actions */
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
export const FETCH_PRODUCTS_START = 'FETCH_PRODUCTS_START'
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS'
export const FETCH_PRODUCTS_FAIL = 'FETCH_PRODUCTS_FAIL'

export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT'
export const FETCH_SINGLE_PRODUCT_START = 'FETCH_SINGLE_PRODUCT_START'
export const FETCH_SINGLE_PRODUCT_SUCCESS = 'FETCH_SINGLE_PRODUCT_SUCCESS'
export const FETCH_SINGLE_PRODUCT_FAIL = 'FETCH_SINGLE_PRODUCT_FAIL'

export const FETCH_CART = 'FETCH_CART'
export const FETCH_CART_START = 'FETCH_CART_START'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_FAIL = 'FETCH_CART_FAIL'

export const CART_ADD_PRODUCT = 'CART_ADD_PRODUCT'
export const CART_ADD_PRODUCT_START = 'CART_ADD_PRODUCT_START'
export const CART_ADD_PRODUCT_SUCCESS = 'CART_ADD_PRODUCT_SUCCESS'
export const CART_ADD_PRODUCT_FAIL = 'CART_ADD_PRODUCT_FAIL'

export const CART_DELETE_PRODUCT = 'CART_DELETE_PRODUCT'
export const CART_DELETE_PRODUCT_START = 'CART_DELETE_PRODUCT_START'
export const CART_DELETE_PRODUCT_SUCCESS = 'CART_DELETE_PRODUCT_SUCCESS'
export const CART_DELETE_PRODUCT_FAIL = 'CART_DELETE_PRODUCT_FAIL'

/* Admin actions */
export const ADMIN_STATE_INIT = 'ADMIN_STATE_INIT'

export const FETCH_ADMIN_PRODUCTS = 'FETCH_ADMIN_PRODUCTS'
export const FETCH_ADMIN_PRODUCTS_START = 'FETCH_ADMIN_PRODUCTS_START'
export const FETCH_ADMIN_PRODUCTS_SUCCESS = 'FETCH_ADMIN_PRODUCTS_SUCCESS'
export const FETCH_ADMIN_PRODUCTS_FAIL = 'FETCH_ADMIN_PRODUCTS_FAIL'

export const FETCH_ADMIN_SINGLE_PRODUCT = 'FETCH_ADMIN_SINGLE_PRODUCT'
export const FETCH_ADMIN_SINGLE_PRODUCT_START = 'FETCH_ADMIN_SINGLE_PRODUCT_START'
export const FETCH_ADMIN_SINGLE_PRODUCT_SUCCESS = 'FETCH_ADMIN_SINGLE_PRODUCT_SUCCESS'
export const FETCH_ADMIN_SINGLE_PRODUCT_FAIL = 'FETCH_ADMIN_SINGLE_PRODUCT_FAIL'

export const ADMIN_ADD_PRODUCT = 'ADMIN_ADD_PRODUCT'
export const ADMIN_ADD_PRODUCT_START = 'ADMIN_ADD_PRODUCT_START'
export const ADMIN_ADD_PRODUCT_SUCCESS = 'ADMIN_ADD_PRODUCT_SUCCESS'
export const ADMIN_ADD_PRODUCT_FAIL = 'ADMIN_ADD_PRODUCT_FAIL'

export const ADMIN_DELETE_PRODUCT = 'ADMIN_DELETE_PRODUCT'
export const ADMIN_DELETE_PRODUCT_START = 'ADMIN_DELETE_PRODUCT_START'
export const ADMIN_DELETE_PRODUCT_SUCCESS = 'ADMIN_DELETE_PRODUCT_SUCCESS'
export const ADMIN_DELETE_PRODUCT_FAIL = 'ADMIN_DELETE_PRODUCT_FAIL'

export const ADMIN_EDIT_PRODUCT = 'ADMIN_EDIT_PRODUCT'
export const ADMIN_EDIT_PRODUCT_START = 'ADMIN_EDIT_PRODUCT_START'
export const ADMIN_EDIT_PRODUCT_SUCCESS = 'ADMIN_EDIT_PRODUCT_SUCCESS'
export const ADMIN_EDIT_PRODUCT_FAIL = 'ADMIN_EDIT_PRODUCT_FAIL'
